---
title: "Data Analytics"
author: "Segah Mir"
date: "07/01/2016"
output:
  html_document:
    highlight: tango
    toc: true
    toc_float:
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
We focus on high value-added data projects at rapidly growing technology companies.

Our engagement process is very thorough It involves a deep conversation with a technical member of our staff. Sales people are not and will never be involved. To make sure that's the case, we have a working EQ (i.e. Empathy IQ) engine for all written conversations. Yes, we are very serious about this "no-sales" commitment.

## Analytics

Google BigQuery is a [partner technology](https://cloud.google.com/partners/directory/#?q=caura#search). We have completed many BQ projects of different complexity (both in Legacy and StandardSQL).

Some links:
<a href="https://discourse.looker.com/t/developer-and-production-pdts-in-looker/3567">link1</a>, <a href="https://discourse.looker.com/t/bigquery-migrating-from-legacy-sql-to-standard-sql/3568">link2</a>, <a href="https://discourse.looker.com/t/incremental-pdts-on-bigquery-or-how-to-produce-daily-snapshots-on-scd-type-1-schemas/2666">link3</a>, <a href="https://stackoverflow.com/questions/35807572/bigquery-pivot-data-rows-columns/43711803#43711803">link4</a>, <a href="https://stackoverflow.com/questions/42151828/google-bigquery-taking-too-long-but-small-change">link5</a>

We also have a close relationship with Looker. This [post](https://segah.me/post/why-did-i-become-a-data-consultant-and-a-looker-partner/) from 2016 might be helpful. On the list of topics: visit [this Looker Discourse page](https://discourse.looker.com/users/segahm/activity/topics).

R is our favorite tool. We like using R in almost all projects. We even pushed it into  [corporate thinking](https://looker.com/blog/predict-lending-clubs-loan-portfolio-returns-using-hp-vertica-looker-and-distributed-r).

## Data Warehousing

When strong data governance is in place, we can help make proactive recommendations using [traditional approach](https://discourse.looker.com/t/designing-a-data-warehouse-what-would-a-bi-solution-recommend/1231/5) and helping you put plans into place to maintain the architecture [post-deployment](https://discourse.looker.com/t/optimize-query-performance-with-lookml-a-case-study/1219).

At many companies the above no longer is feasible. We can help with long-term process and plan to monitor performance objectives against analytical needs.

## DNN, NLP

This is becoming a growing field for us. Please contact for further details or see our [partner product](/entropy).
